import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import UserButton from '@/components/UserButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex w-full py-2  border-b justify-center'>
          <div className='flex w-5/6 justify-between items-center'>
            <div className='space-x-6'>
              <Link className="text-xl" href='/'>GTC RAG</Link>
              <Link href='/ask'>Ask</Link>
              <Link href='/documents-library'>Library</Link>
            </div>
            <div className='self-end'>
              <UserButton />
            </div>
          </div>

        </div>

        {children}
      </body>
    </html>
  )
}
