import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex w-full p-6 space-x-6 border-b'>
          <Link href='/'>GTC RAG</Link>
          <Link href='/ask'>Ask</Link>
          <Link href='/documents-library'>Library</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
